name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    # Runs at 12am UTC
    - cron: '*/5 * * * *'

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_TITLE: "true"
          BLOCKS: ->
          TIME_RANGE: all_time
          SHOW_PROJECTS: "true"
          SHOW_TIME: "true"
          SHOW_TOTAL: "true"
          SHOW_LINES_OF_CODE: "true"
          SHOW_TOTAL_CODE_TIME: "true"
          SHOW_COMMIT: "true"

