
name: Waka Readme

on:
  schedule:
    # Runs at 12am IST
    - cron: '*/12 * * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses:  barthachijuu/waka-profile-stats@main
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_COMMIT: "True"
          SHOW_PROJECTS: "True"
          SHOW_LANGUAGE: "True"
         
          
